xctool/xctool/AnalyzeAction.m

With Xcode 6 it seems build-state.dat is not generated anymore.
As the TextReporter was parsing it to find StaticAnalyzer plist file to show analyze summary, this was not working anymore.
I added a small search function to find the output plist and build analyze summary as before.

Fix StaticAnalyzer plist files search 

---

xctool/xctool/RunTestsAction.m

Previously the main thread was sitting idle while waiting for logic
tests to finish. We might as well use that time to kick off the
application tests.

Run logic tests in parallel with application tests

---

otest-query/OtestQuery/OtestQuery.m

otest queries were crashing for me. The tests contain a lot of C++ code and static initializers, which might explain the problem. There were a lot of messages about ARC probes in the log, but after the (correct) results were printed. From the description of the query injection process it seems to me that exit should be as fast as possible, so I replaced exit() with _exit().

Exit otest query using _exit to prevent calling atexit handlers

---

xctool/xctool/main.m

Fixes #471
When unset, `DYLD_FALLBACK_FRAMEWORK_PATH` can't simply be treated as empty, as dyld will impose some default paths in that case. Hence when we set it, we want to maintain those defaults.
From `man dyld`:
>        DYLD_FALLBACK_FRAMEWORK_PATH
>              This  is  a  colon separated list of directories that contain frameworks.  It is used as the default location
>              for frameworks not found in their install path.
>
>              By default, it is set to /Library/Frameworks:/Network/Library/Frameworks:/System/Library/Frameworks

include default paths when setting DYLD_FALLBACK_FRAMEWORK_PATH

---

xctool/xctool/OCUnitIOSAppTestRunner.m
xctool/xctool/SimulatorWrapper/SimulatorWrapperXcode6.m

Simulator environment is already copied for logic tests but weren't doing that when running application tests.
In this PR I am updating that behaviour. Tricky part here is that priority of simulator environment should have lower priority then the one set by xctool. But in that case `TMPDIR` would have the value passed to xctool which is wrong. To fix that we are overriding `TMPDIR` environment value with the one given by the simulator device.

Copy simulator environment and override TMPDIR value when running app tests

---

xctool/xctool/TaskUtil.h
xctool/xctool/TaskUtil.m
xctool/xctool/XCToolUtil.h
xctool/xctool/XCToolUtil.m

When xcodebuild crashes xctool doesn't print any errors or warnings.
For example, before this fix output would be something like:
[Info] Loading settings for scheme 'TestXcode6iOs8' ... (3415 ms)
=== TEST ===
xcodebuild build build
** TEST FAILED: 0 passed, 0 failed, 0 errored, 0 total ** (967 ms)
After the fix:
=== BUILDING XCTOOL ===
/Users/nekto/Projects/xctool/scripts/build.sh
✓ Built xctool (11000 ms)
[Info] Loading settings for scheme 'TestXcode6iOs8' ... (3429 ms)
=== TEST ===
xcodebuild build build
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
xcodebuild crashed when running the task below:
<NSTask string representation>
Latest available xcodebuild crash report …

Improve error output when xcodebuild crashes

---

xctool/xctool-tests/FakeTaskManager.m
xctool/xctool-tests/LaunchHandlers.h
xctool/xctool-tests/LaunchHandlers.m
xctool/xctool-tests/Options+Testing.h
xctool/xctool-tests/Options+Testing.m
xctool/xctool-tests/OptionsTests.m
xctool/xctool-tests/RunTestsActionTests.m
xctool/xctool.xcodeproj/project.pbxproj
xctool/xctool/OCUnitIOSLogicTestRunner.m
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/Options.h
xctool/xctool/Options.m
xctool/xctool/RunTestsAction.h
xctool/xctool/RunTestsAction.m
xctool/xctool/SimulatorWrapper/SimulatorInfo.m
xctool/xctool/SimulatorWrapper/SimulatorInfoXcode6.m
xctool/xctool/SimulatorWrapper/SimulatorWrapperXcode6.m
xctool/xctool/TestRunning.h
xctool/xctool/TestableExecutionInfo.h
xctool/xctool/TestableExecutionInfo.m
xctool/xctool/XCTool.m
xctool/xctool/XCToolUtil.h
xctool/xctool/XCToolUtil.m

In this series of diffs, I add support for running logic and application test bundles directly from xctool, without scraping data from Xcode projects and schemes.
I also included a tweak to make running application tests with the iOS Simulator from Xcode 6 more pleasant: we now launch the simulator in the background and do not steal focus.
Lots of unit tests included.

Add support for running logic and app test bundles directly, without Xcode projects

---

xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool/OCUnitOSXAppTestRunner.m
xctool/xctool/OCUnitOSXLogicTestRunner.m

When running OS X test bundles without a project directory, we hit an assertion failure in the OS X test runners when they tried to chdir to `Xcode_PROJECT_DIR` and it wasn't present. This makes that behavior optional, and fixes running OS X tests from Buck.

Make OS X test chdir to Xcode PROJECT_DIR optional

---

.buckconfig
.gitignore
.travis.yml
.watchmanconfig
BUCK
scripts/create_xctool_zip.sh
scripts/travis-ci.sh

This doesn't yet build the mobile-installation-helper.app, but that's next.
I'm thinking about how we might want to run xctool tests via Buck. Maybe directly with `xctest`?
I tested this with:
```
% buck build :xctool-zip
% unzip -l buck-out/gen/xctool.zip
Archive:  buck-out/gen/xctool.zip
Length     Date   Time    Name
--------    ----   ----    ----
0  05-27-15 21:28   bin/
690468  05-27-15 21:28   bin/xctool
0  05-27-15 21:28   lib/
59004  05-27-15 21:28   lib/otest-query-lib-ios.dylib
62868  05-27-15 21:28   lib/otest-query-lib-osx.dylib
102496  05-27-15 21:28   lib/otest-shim-ios.dylib
106360  05-27-15 21:28   lib/otest-shim-osx.dylib
39668  05-27-15 21:28   lib/sim-shim.dylib
0  05-27-15 21:28   libexec/
0  05-27-15 21:28   libexec/mobile-installation-helper.app/
24896  05-27-15 …
```

Allow xctool to build with Buck

---

scripts/create_xctool_zip.sh

The build is currently broken with Buck master:
https://travis-ci.org/facebook/xctool/builds/65782394
This is because Buck commit c83489ea543ce164d43dd93a1af53c76ea45e139 changed the behavior of the `apple_bundle` rule to no longer output a ZIP archive, but instead place its output directly in a directory.
This updates `scripts/create_xctool/zip.sh` to work with the new behavior.
Tested with `buck build //:xctool-zip`.

Don't unzip output of apple_bundle rule

---

Common/TestingFramework.m
README.md
xctool/xctool/XCTool.m

Why now:
- At Facebook we aren't using Xcode 5.
- Travis CI uses Xcode 6.1.1 since December 18th, 2014 ((http://docs.travis-ci.com/user/osx-ci-environment/#Xcode, http://docs.travis-ci.com/user/build-environment-updates/2014-12-18/).
- According to Apple documentation (https://developer.apple.com/support/xcode/) developers "should use the latest version of Xcode available on the Mac App Store to submit your apps, or when available, the latest GM seed release from the Xcode download page.". Latest version in the Mac App Store is 6.3.2 (https://itunes.apple.com/us/app/xcode/id497799835?mt=12).
- Latest Xcode 5 version (5.1.1) was released more then a year ago (http://en.wikipedia.org/wiki/Xcode#Xcode_5.0_-_7.x_.28with_arm64_support.29)
Benefits:
- We could switch from injecting dynamic …

Drop Xcode 5 support.

---

xctool/xctool-tests/ActionScriptsTests.m
xctool/xctool-tests/TestData/TestProject-Library-OSX/TestProject-Library-OSX.xcodeproj/xcshareddata/xcschemes/TestProject-Library-OSX-With-Scripts.xcscheme
xctool/xctool.xcodeproj/project.pbxproj
xctool/xctool/ActionScripts.h
xctool/xctool/ActionScripts.m
xctool/xctool/AnalyzeAction.m
xctool/xctool/ArchiveAction.m
xctool/xctool/BuildAction.m
xctool/xctool/BuildTestsAction.m
xctool/xctool/Options.h
xctool/xctool/Options.m
xctool/xctool/RunTestsAction.m
xctool/xctool/XcodeSubjectInfo.h
xctool/xctool/XcodeSubjectInfo.m

Fixes Issue #313 
Feature is enabled by using `-actionScripts`
All comments welcome, especially on file placement, naming conventions, and hook placement.
Signed-off-by: Jimi Xenidis <jimix@pobox.com>

Run available pre and post actions scripts in the active scheme

---

reporters/teamcity/TeamCityReporter.m

I reported Issue #540 with a stack trace I was getting on build errors (instead of the error)

Check for empty error outputText in TeamCity reporter

---

README.md
xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.m
xctool/xctool/TestAction.m

In addition to specifying specific test classes with `only` argument, this change allows you to specify a class prefix, which is useful if you want to run a number of test classes that are logically connected, which share the same prefix.
For example if you have test cases
```
WesterosNorthTestClass
WesterosEastTestClass
WesterosSouthTestClass
```
instead of specifying the 3 classes explicitly, you can just do `-only SomeTarget:Westeros*`

Allow prefix matching for test class names

---

BUCK
xctool/xctool/XCToolUtil.m

This fixes the following build issues when building from Buck:
```
third-party/ios/xctool/xctool/xctool/SimulatorWrapper/SimulatorUtils.m:33:31: warning: 'launch_data_alloc' is deprecated: first deprecated in OS X 10.10 [-Wdeprecated-declarations]
launch_data_t stopMessage = launch_data_alloc(LAUNCH_DATA_DICTIONARY);
```
and
```
third-party/ios/xctool/xctool/xctool/XCToolUtil.m:355:60: error: use of undeclared identifier 'LONG_LONG_MIN'
__attribute__((__blocks__(byref))) long long errorCode = LONG_LONG_MIN;
```

Fix a few BUCK build issues

---

BUCK

The `BUCK` file doesn't link in XCTest, so when running xctool built by Buck you get:
```
2015-09-14 20:15:22.715 xctool[89573:7208158] *** Assertion failure in -[OCUnitIOSAppTestRunner testEnvironmentWithSpecifiedTestConfiguration], third-party/ios/xctool/xctool/xctool/OCUnitTestRunner.m:333
2015-09-14 20:15:22.787 xctool[89573:7208158] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'XCTestConfiguration isn't available'
```

Fix the Buck build.

---

BUCK

Genrules infer dependencies referenced in the command via macros automatically.

Remove explicit deps from genrules.

---

xctool/xctool-tests/BuildTestsActionTests.m
xctool/xctool-tests/RunTestsActionTests.m
xctool/xctool-tests/TestActionTests.m
xctool/xctool/BuildTestsAction.h
xctool/xctool/BuildTestsAction.m
xctool/xctool/RunTestsAction.h
xctool/xctool/RunTestsAction.m
xctool/xctool/TestAction.m
xctool/xctool/TestActionInternal.h

Add a command line option to omit particular tests using the same format as the -only flag.  Add omitted targets/tests to the skipped targets/tests from the scheme.
In "testCanSelectSpecificTestClassOrTestMethodWithOnly", "runWithOnlyArgumentAndExpectSenTestToBe" was taking in a list of expected tests, but it was doing absolutely nothing with them.  So, stop sending them in since they're ignored anyway.
Generalize "onlyListAsTargetsAndSenTestList" and make it return a dictionary rather than an array of key value pairs so that we can query whether a given target is in it or not easily.

Add an omit option for tests

---

xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool-tests/OTestShimTests.m
xctool/xctool/OCUnitIOSAppTestRunner.m
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.h
xctool/xctool/RunTestsAction.m
xctool/xctool/TestAction.m

I added a option for disabling the reseting of the simulator if the install failed 3 times.

Add option for not reseting the simulator on failure

---

otest-shim/otest-shim/otest-shim.m

This disables some sort of symbolication feature new in xctest in xcode7. This feature hangs nondeterministically when a test throws an objc exception:
```
0   libsystem_platform.dylib      	0x030e0500 _platform_memcmp + 48
1   com.apple.CoreSymbolication   	0x25cbc703 0x25c8a000 + 206595
2   com.apple.CoreSymbolication   	0x25ca1951 0x25c8a000 + 96593
3   com.apple.CoreSymbolication   	0x25c93725 0x25c8a000 + 38693
4   com.apple.CoreSymbolication   	0x25cbb2c1 0x25c8a000 + 201409
5   com.apple.CoreSymbolication   	0x25cba12b 0x25c8a000 + 196907
6   com.apple.CoreSymbolication   	0x25cbaa06 0x25c8a000 + 199174
7   com.apple.CoreSymbolication   	0x25ca175f CSSymbolicatorCreateWithPathArchitectureFlagsAndNotification + 233
8   com.apple.CoreSymbolication   	0x25ca8772 0x25c8a000 + 124786
9 …
```

disable xctest symbolication in xcode7 because it sometimes hangs

---

README.md
reporters/text/TextReporter.h
reporters/text/TextReporter.m
reporters/text/main.m

This implements #512. I'm not sure if this is how you would like the
feature implemented, happy to iterate.

Allow pretty reporting without overwrite when TTY not detected.

---

xctool/xctool/TaskUtil.m

Fixes an occasional crash when `poll()` failed due to an interruption.

hand EINTR from poll()

---

xctool/xctool-tests/BuildActionTests.m
xctool/xctool-tests/OptionsTests.m
xctool/xctool/BuildAction.h
xctool/xctool/BuildAction.m

`-dry-run` option is very useful in combination with json-compilation-database reporter when we need the `compile_commands.json` file but there is no need to build the project. With `-dry-run`, it only prints the commands without executing them, dramatically reducing the amount of time needed to get the `compile_commands.json` file.

Add support for -dry-run option

---

xctool/xctool-tests/BuildActionTests.m
xctool/xctool/BuildAction.h
xctool/xctool/BuildAction.m

`skipUnavailableActions` is a useful option when you want to obtain the `compile_commands.json` file no matter if all the build actions can be performed or not. One can find other useful use cases.

Add support for '-skipUnavailableActions' option

---

xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool-tests/OTestShimTests.m
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.m

We'd like to pass through environment variables from Buck when running iOS / OS X tests. (For example, we'd like to set an environment variable telling the test where to write its log files).
This adds the ability to set environment variables named `XCTOOL_TEST_ENV_FOO` when running tests via `xctool`. It will pass through any such environment variable after stripping the `XCTOOL_TEST_ENV_` prefix.
Added unit tests and confirmed they passed by running `./scripts/make_release.sh`. Also integrated with Buck and confirmed via simulator logs that environment variables were passed through.

Test passthrough for process environment variables named XCTOOL_TEST_ENV_*

---

reporters/junit/JUnitReporter.m

The junit reporter sometimes generates a `junit.xml` that's not valid xml. This is an attempt to make sure the created `junit.xml` is always valid.

Make junit reporter output valid UTF8 to not break Jenkins' junit plugin.

---

BUCK

If a .buckconfig were to enable -Wundeclared-selector or -Wimplicit-retain-self with -Werror, xctool would stop building. Explicitly disable these warnings.

Add compiler flags to allow building in distinct environments

---

xctool/Headers/CoreSimulator/SimDeviceType.h
xctool/xctool/SimulatorWrapper/SimulatorInfo.m

Problem was SimDeviceType removed the +supportedDeviceTypesByName method.

Fixes #632, in which an exception is raised on invalid destinations

---

Common/XCToolUtil.m
otest-query/otest-query.xcodeproj/project.pbxproj
otest-shim/otest-shim.xcodeproj/project.pbxproj
reporters/reporters-tests/reporters-tests-Info.plist
reporters/reporters.xcodeproj/project.pbxproj
reporters/user-notifications/user-notifications-Info.plist
xcodebuild-shim/xcodebuild-shim.xcodeproj/project.pbxproj
xctool/xctool-tests/FakeSimDevice.h
xctool/xctool-tests/FakeSimDevice.m
xctool/xctool-tests/SimulatorWrapperTests.m
xctool/xctool-tests/xctool-tests-Info.plist
xctool/xctool.xcodeproj/project.pbxproj
xctool/xctool.xcodeproj/xcshareddata/xcschemes/xctool.xcscheme
xctool/xctool/OCUnitIOSAppTestRunner.m
xctool/xctool/SimulatorWrapper/SimulatorUtils.h
xctool/xctool/SimulatorWrapper/SimulatorUtils.m
xctool/xctool/SimulatorWrapper/SimulatorWrapper.h
xctool/xctool/SimulatorWrapper/SimulatorWrapper.m
xctool/xctool/SimulatorWrapper/SimulatorWrapperXcode6.m

Next CoreSimulator methods could stuck forever in Xcode 7.1 and Xcode 7.2 beta:
```
- (BOOL)applicationIsInstalled:(NSString *)bundleId type:(NSString **)arg2 error:(NSError **)error;
- (BOOL)installApplication:(NSURL *)appURL withOptions:(NSDictionary *)options error:(NSError **)error;
- (BOOL)uninstallApplication:(NSString *)bundleId withOptions:(NSDictionary *)options error:(NSError **)error;
- (int)launchApplicationWithID:(id)arg1 options:(NSDictionary *)options error:(NSError **)error;
- (BOOL)eraseContentsAndSettingsWithError:(id *)arg1;
- (BOOL)shutdownWithError:(id *)arg1;
```
Since xctool executes them on the main thread it can put the tool into a deadlock. To avoid that we will wait for CoreSimulator responses only a particular amount of time and then "forget" about them and try …

Wait for CoreSimulator responses only a particular amount of time.

---

xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool-tests/OTestShimTests.m
xctool/xctool/OCUnitIOSAppTestRunner.m
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.h
xctool/xctool/RunTestsAction.m
xctool/xctool/SimulatorWrapper/SimulatorWrapper.h
xctool/xctool/SimulatorWrapper/SimulatorWrapper.m
xctool/xctool/SimulatorWrapper/SimulatorWrapperXcode6.m
xctool/xctool/TestAction.m

Adding the `NSWorkspaceLaunchNewInstance` launch option to the NSRunningApplication allows multiple simulators instances to be run concurrently on a single machine.

Open new instance of Simulator to allow parallelizing UI tests

---

otest-query/otest-query.xcodeproj/project.pbxproj
otest-shim/otest-shim.xcodeproj/project.pbxproj
reporters/reporters.xcodeproj/project.pbxproj
xcodebuild-shim/xcodebuild-shim.xcodeproj/project.pbxproj
xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool-tests/XcodeSubjectInfoTests.m
xctool/xctool.xcodeproj/project.pbxproj
xctool/xctool.xcodeproj/xcshareddata/xcschemes/xctool.xcscheme
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.m
xctool/xctool/Testable.h
xctool/xctool/Testable.m
xctool/xctool/XcodeSubjectInfo.m

This PR addresses a bug described in https://github.com/facebook/xctool/issues/657. But also improves  wordings and data flow in xctool.

Improve `-only` and `-omit` options behavior.

---

xctool/xctool/BuildTestsAction.h
xctool/xctool/BuildTestsAction.m

This might help people working around #248 by passing `-derivedDataPath` to `build-tests` (which was ignored before):
1st run:
```
$ ~/Development/xctool/scripts/xctool.sh -scheme 'eBay Kleinanzeigen' -derivedDataPath /tmp/foo build-tests -only 'Unit Tests' -sdk iphonesimulator
...
** BUILD-TESTS SUCCEEDED ** (138066 ms)
```
2nd run:
```
$ ~/Development/xctool/scripts/xctool.sh -scheme 'eBay Kleinanzeigen' -derivedDataPath /tmp/foo build-tests -only 'Unit Tests' -sdk iphonesimulator
...
** BUILD-TESTS SUCCEEDED ** (39262 ms)
```

Pass derivedDataPath to BuildTestsAction

---

README.md

1.'omit' is used for example here;
https://github.com/facebook/xctool/pull/663
2.There may be a bug/feature missing; it did not work to add a list of items with 'omit'.

DOC: Add 'omit' syntax.

---

xctool/xctool/RunTestsAction.m

If you pass `-destination 'id=UDIDSTRING'` it was trying to use a different
Simulator device for collecting the test cases. This commit fixes this
issue.

Fix missing deviceName and OSVersion

---

xctool/xctool-tests/OptionsTests.m
xctool/xctool/Options.m

xcodebuild bails if the path provided to `resultBundlePath` exists already, so the current behavior for xctool is backwards (in terms of rejecting a path that doesn't already exist). When presented with a result bundle path that already exists, xcodebulid exits with the error: `xcodebuild: error: Existing file at -resultBundlePath`.
It seems like xcodebuild has the same behavior back to Xcode 6.4, based on brief testing, so I'm kinda curious if this option ever worked?

Assert that resultBundlePath does not exist

---

otest-shim/otest-shim/otest-shim.m
xctool/xctool-tests/OCUnitTestRunnerTests.m
xctool/xctool-tests/OTestShimTests.m
xctool/xctool-tests/TestRunStateTests.m
xctool/xctool/OCUnitTestRunner.h
xctool/xctool/OCUnitTestRunner.m
xctool/xctool/RunTestsAction.h
xctool/xctool/RunTestsAction.m
xctool/xctool/TestAction.m
xctool/xctool/TestRunState.m

This resolves #614 and addresses the feedback in #629.
The `--wait-for-debugger` option doesn't actually work for launching iOS app test targets. My workaround that seems to work for all test targets is to simply print a message from within the test app just before starting to run tests, and then raise a SIGSTOP which halts execution.

Option to wait for debugger on launch

---

xctool/xctool/SimulatorWrapper/SimulatorInfo.m

**background**
After upgrading to Xcode 8.3.3, xctool would fail when targeting simulators with "Unable to find SDK for platform iphonesimulator and sdk version 10.3.1", even though the 10.3 sdk was installed.
This issue is caused by `-[SimRuntime versionString]` including the patch version of the sdk, while the sdk's `SDKSettings.plist` includes only the major and minor version.
**change**
When comparing the version as reported by `SimRuntime` to the versions pulled from the sdk's plist, ignore the patch version.
**verification**

Fix simulator SDK not found in Xcode 8.3.3

---

Common/TestingFramework.h
Common/TestingFramework.m
Common/XCToolUtil.h
Common/XCToolUtil.m
xctool/xctool/OCUnitIOSLogicTestRunner.m

As mentioned by @aaronclarke in #732, the path for `xctest` has changed in Xcode 9. This was my first pass at getting this to work. It might need further work since I think it's odd to leave `kTestingFrameworkIOSTestrunnerName` pointing to `usr/bin/xctest`, but I think I need a little more guidance from the project maintainers on how this should be done.

Update launchPath for xctest when run against Xcode 9

---

xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/Core.xcodeproj/project.pbxproj
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/Core.xcodeproj/project.xcworkspace/contents.xcworkspacedata
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/Core.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/Core/Core.h
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/Core/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/CoreTests/CoreTests.swift
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Core/CoreTests/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject.xcodeproj/project.pbxproj
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject.xcodeproj/xcshareddata/xcschemes/MainProject.xcscheme
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/AppDelegate.h
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/AppDelegate.m
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/Assets.xcassets/AppIcon.appiconset/Contents.json
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/Assets.xcassets/Contents.json
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/Base.lproj/MainMenu.xib
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/MainProject.entitlements
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProject/main.m
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProjectTests/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/MainProject/MainProjectTests/MainProjectTests.m
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/TestingCore/TestingCore.xcodeproj/project.pbxproj
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/TestingCore/TestingCore/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/TestingCore/TestingCore/TestingCore.h
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/TestingCore/TestingCoreTests/Info.plist
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/TestingCore/TestingCoreTests/TestingCoreTests.swift
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Untitled.xcworkspace/contents.xcworkspacedata
xctool/xctool-tests/TestData/TestProject-RecursiveDefinitions/Untitled.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
xctool/xctool-tests/XcodeSubjectInfoTests.m
xctool/xctool/XcodeSubjectInfo.m

Current state:
*xctool* will fail to resolve project path on projects which have `recursive-like` dependencies.
Consider this dependency graph:
```
*MainProject.xcodeproj*
- MainProjectApp target -> Core
- MainProjectTests target -> TestingCoreFramework
*Core.xcodeproj*
- CoreFramework target
- CoreFrameworkTestst target -> TestingCore
*TestingCore.xcodeproj*
- TestingCoreFramework target -> Core
- TestingCoreFrameworkTests target
```
if we build one target at a time, there'll be no dependency cycle. But Xctool resolves paths for *all* projects and *all* targets, So now, when xctool tries to resolve all subprojects paths it will end up with this cycle:
```
*Core* depends on *TestingCore* (in CoreFrameworkTests rarget)
- *CoreFrameworkTests* depends on Core (in TestingCoreFramework target) …
```

Fix case, when paths cannot be resolved because of recursive-like dependencies

---

xctool/xctool/SimulatorWrapper/SimulatorTaskUtils.m

This is to address #766 .
Before Xcode 11, `simctl spawn` will automatically run in standalone mode if the device is not booted. Xcode 11 starts requiring `--standalone` to be explicit. Since `--standalone` also works on older version of Xcode, I just simply add it to the `spawn` task.
If a simulator is already booted, passing `--standalone` will cause some test cases fail, so it's only added when simulator is not booted.

Xcode 11 fix (add --standalone to spawn) 
